#!/usr/bin/env bash
# Creates ~/.mcp-env from student-label-system MONGODB_URI (does not print secrets).
set -euo pipefail

PROJECT_ROOT="$(cd "$(dirname "$0")/.." && pwd)"
MCP_ENV="$HOME/.mcp-env"
ZSHRC="$HOME/.zshrc"

load_uri() {
  node -e "
const { readFileSync, existsSync } = require('fs');
const { resolve } = require('path');
const root = process.argv[1];
for (const file of ['.env.local', '.env']) {
  const path = resolve(root, file);
  if (!existsSync(path)) continue;
  for (const line of readFileSync(path, 'utf8').split('\n')) {
    const trimmed = line.trim();
    if (!trimmed || trimmed.startsWith('#')) continue;
    const eq = trimmed.indexOf('=');
    if (eq === -1) continue;
    const key = trimmed.slice(0, eq).trim();
    if (key !== 'MONGODB_URI') continue;
    let value = trimmed.slice(eq + 1).trim();
    if ((value.startsWith('\"') && value.endsWith('\"')) || (value.startsWith(\"'\") && value.endsWith(\"'\"))) {
      value = value.slice(1, -1);
    }
    process.stdout.write(value);
    process.exit(0);
  }
}
process.exit(1);
" "$PROJECT_ROOT"
}

URI="$(load_uri)" || {
  echo "ERROR: MONGODB_URI not found in $PROJECT_ROOT/.env or .env.local" >&2
  exit 1
}

# Escape double quotes for safe embedding in double-quoted bash export
ESCAPED_URI="${URI//\\/\\\\}"
ESCAPED_URI="${ESCAPED_URI//\"/\\\"}"

cat > "$MCP_ENV" <<EOF
# MongoDB MCP Server Configuration (generated by scripts/setup-mongodb-mcp-env.sh)
# Do not commit this file.
export MDB_MCP_CONNECTION_STRING="$ESCAPED_URI"
export MDB_MCP_READ_ONLY="true"
EOF

chmod 600 "$MCP_ENV"

if [[ -f "$ZSHRC" ]] && ! grep -q 'source ~/.mcp-env' "$ZSHRC" 2>/dev/null; then
  printf '\n# MongoDB MCP (Cursor)\nsource ~/.mcp-env\n' >> "$ZSHRC"
  echo "Added source ~/.mcp-env to $ZSHRC"
elif [[ ! -f "$ZSHRC" ]]; then
  printf '# MongoDB MCP (Cursor)\nsource ~/.mcp-env\n' > "$ZSHRC"
  echo "Created $ZSHRC with source ~/.mcp-env"
else
  echo "source ~/.mcp-env already present in $ZSHRC"
fi

echo "Created $MCP_ENV (mode 600)"
echo "Verify in a new terminal:"
echo '  env | grep "^MDB_MCP" | sed "/^MDB_MCP_READ_ONLY=/!s/=.*/=[set]/"'
